[package]
name = "RustGitFolder"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "main_program"
path = "src/main.rs"

[[bin]]
name = "3"  
path = "src/rustBookCh3.rs"

[dependencies]
rand = "0.8.5"